version: "3.7"

services:
    mysql:
        image: mysql:latest
        container_name: adm_videos_mysql
        restart: always
        tty: true
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=123456
            - MYSQL_DATABASE=adm_videos
        security_opt:
            - seccomp:unconfined
        networks:
            - adm_videos_network

networks:
    adm_videos_network:
